import { Preset } from "../interface/state";
import { defaultParams } from "./default-params";

export const electricPiano: Preset = {
  ...defaultParams,
  displayName: "Electric piano",
  delay: {
    length: 0.51,
    feedback: 0.5,
    mix: 0.1,
    pingPong: 1,
  },
  envelopes: [
    {
      amount: 1,
      target: "amplitude",
      tension: 1,
      A: 0.001,
      D: 0.7,
      S: 0.2,
      R: 0.5,
    },
    {
      amount: 1,
      target: "FM_0_amp",
      tension: 0.7,
      A: 0,
      D: 0.4,
      S: 0,
      R: 0.2,
    },
    {
      amount: 1,
      target: "FM_1_amp",
      tension: 0.8,
      A: 0,
      D: 0.5,
      S: 0,
      R: 0.2,
    },
    {
      amount: 1,
      target: "FM_2_amp",
      tension: 0,
      A: 0,
      D: 0.9,
      S: 0,
      R: 0.2,
    },
  ],
  FMOscs: [
    {
      id: "1641843649562",
      gain: 40,
      ratio: 24,
      target: "0",
      type: "sine",
    },
    {
      id: "1641843717250",
      gain: 20,
      ratio: 12,
      target: "1",
      type: "sine",
    },
    {
      id: "1641843804106",
      gain: 2,
      ratio: 1,
      target: "2",
      type: "sine",
    },
  ],
  LFOs: [],
  master: {
    dcOffset: 0,
    EQHigh: 0,
    EQLow: 6,
    gain: 0.2,
    transpose: 0,
  },
  oscillators: [
    {
      id: "1641843644106",
      options: {
        balance: 0,
        coarse: 0,
        fine: 0,
        gain: 0.04,
        octave: 0,
        unison: 1,
        detuneU: 0.1,
        widthU: 0.1,
        phase: 0,
      },
      type: "sine",
    },
    {
      id: "1641843704067",
      options: {
        balance: 0,
        coarse: 0,
        fine: 0,
        gain: 0.04,
        octave: 0,
        unison: 1,
        detuneU: 0.1,
        widthU: 0.1,
        phase: 0,
      },
      type: "sine",
    },
    {
      id: "1641843751379",
      options: {
        balance: 0,
        coarse: 0,
        fine: 0,
        gain: 1,
        octave: 0,
        unison: 4,
        detuneU: 8,
        widthU: 1,
        phase: 1,
      },
      type: "sine",
    },
  ],
  velocity: {
    scale: 1.2,
    offset: 0,
    virtual: 0.5,
    targets: {
      FM_0_amplitude: 1,
      FM_1_amplitude: 1,
      FM_2_amplitude: 1,
      amplitude: 0,
    },
  },
};
